version: 2.1
orbs:
  android: circleci/android@2.0
jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    environment:
              KEYSTORE_FILE: ./app/build/MyKeyStore/keyStore.jks
              KEYSTORE_PASSWORD: rfe666
              KEY_ALIAS: KotlinTutorialKey
              KEY_PASSWORD: rfe666
    steps:
      - checkout
      - run:
          name: Set execute permission for gradlew
          command: chmod +x gradlew  # 設定執行權限
      # - run:
      #     name: Change Keystore Directory Permissions
      #     command: chmod -R 755 /Users/1691/MyKeyStore  # 修改資料夾權限
      - run:
          name: Download Dependencies # 確保項目的依賴庫是否正確,確保在不同環境都能編譯
          command: ./gradlew androidDependencies
      - save_cache: #將gradle結果暫存至circleCI快取中 如果沒有變化就不需要重新下載和解析依賴庫
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # - build-debug-apk
      # - build-debug-aab
      - run:
          name: Check Keystore File
          command: ls ./app/build/MyKeyStore/

      - build-release-apk

workflows:
  version: 2
  build-apk-workflow:
    jobs:
      - build

commands:
  build-debug-apk:
    steps:
      - run:
          name: Build APK
          command: ./gradlew assembleDebug #建構debug版本apk
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: app-debug-testName.apk

  build-debug-aab: 
    steps:
      - run:
          name: Build Debug AAB
          command: ./gradlew bundleDebug #建構debug版本aab
      
      - store_artifacts:
          path: app/build/outputs/bundle/debug/app-debug.aab
          destination: debug-app-testName.aab

  build-release-apk:
    steps:
      # - android/restore-gradle-cache
      # - android/restore-build-cache
      #建構release版本apk
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease 
              -Pandroid.injected.signing.store.file=$KEYSTORE_FILE
              -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
              -Pandroid.injected.signing.key.alias=$KEY_ALIAS
              -Pandroid.injected.signing.key.password=$KEY_PASSWORD
              
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          destination: app-release-testName.apk
