# 使用最新2.1版本的CircleCI管道流程引擎
# 參考: https://circleci.com/docs/configuration-reference
version: 2.1

# 定義在job中調用的作業
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test:
    # 指定執行環境。您可以指定來自 Docker Hub 的圖像或使用我們來自 CircleCI 開發人員中心的便利圖像之一
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - say-hello
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # - run-android-unit-test
      # - run:
      #     name: "Say hello"
      #     command: "echo Hello, World!"

commands:
  say-hello:
    steps:
      - run:
          name: "test name"
          command: "test command"

  run-android-unit-test:
    steps:
      - run:
          name: "Grant execute permission to gradlew"
          command: "chmod +x gradlew"
      - run:
          name: "unit test"
          command: "./gradlew testDebug"

# 使用workflows編排作業流程
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - test
