version: 2.1
jobs:
 build:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      # - run:
      #     name: Upload to Cloud Storage
      #     command: |
            # 在這裡加入上傳至雲端的指令

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master